# /// script
# requires-python = ">=3.11"
# dependencies = ["duckdb>=1.4,<2", "pytz"]
# ///
"""Render a self-contained, local HTML report from measured analysis artifacts."""
import json
from pathlib import Path
import duckdb

out=Path('topic-analysis')
spikes=json.loads((out/'topic-spikes.json').read_text())
sentiment=json.loads((out/'sentiment-shifts.json').read_text())
profile=json.loads(Path('twitter-analysis/profile.json').read_text())
notes=json.loads((out/'interpretations.json').read_text())
lookup={r['topic']:r for r in sentiment['topics']}
chosen={r['topic']:r for r in spikes['topics'][:150]}
for r in spikes['topics']:
 if r['topic'].startswith('entity:') or r['topic'] in lookup:chosen[r['topic']]=r
for r in sorted(spikes['topics'],key=lambda x:x['total_tweets'],reverse=True)[:50]:chosen[r['topic']]=r
for r in [r for r in spikes['topics'] if r['low_baseline']][:20]:chosen[r['topic']]=r
c=duckdb.connect()
c.execute("SET TimeZone='UTC'")
cur=c.execute("SELECT topic,id,body,lang,like_count,views_count,created_at FROM read_parquet('topic-analysis/topic-evidence.parquet')")
cols=[r[0] for r in cur.description]
evidence={}
for row in cur.fetchall():
 r=dict(zip(cols,row));evidence.setdefault(r.pop('topic'),[]).append(r)
for topic,r in chosen.items():
 r['sentiment']=lookup.get(topic)
 r['evidence']=evidence.get(topic,[])
 r['interpretation']=notes.get('topics',{}).get(topic)
data={'topics':list(chosen.values()),'sentiment_method':sentiment['method'],'spike_method':spikes['method'],
      'notes':notes,'profile':{'observations':profile['full_coverage'][0]['observations'],
      'tweets':profile['full_exact_ids']['distinct_tweets'],'authors':profile['full_coverage'][0]['distinct_authors']},
      'candidate_topics':spikes['candidate_topics']}
serialized=json.dumps(data,ensure_ascii=False,default=str).replace('<','\\u003c')
html='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Twitter topic, sentiment & traction outliers</title>
<style>
:root{color-scheme:light;--ink:#172c38;--muted:#526675;--line:#d9e2e6;--blue:#146b9e;--red:#a73838;--green:#197254}*{box-sizing:border-box}body{margin:0;background:#f3f6f7;color:var(--ink);font:15px/1.5 system-ui,-apple-system,sans-serif}main{max-width:1280px;margin:auto;padding:36px 24px 70px}h1{font-size:34px;line-height:1.15;letter-spacing:-1px;margin:8px 0 16px}h2{font-size:21px}h3{font-size:17px;margin:0 0 10px}p{margin:8px 0 14px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:1.5px;color:var(--muted)}.muted,small{color:var(--muted)}.stats{display:flex;gap:14px;flex-wrap:wrap;margin:24px 0}.stat{background:white;border:1px solid var(--line);padding:16px 20px;min-width:180px;border-radius:9px}.stat strong{display:block;font-size:24px}.notice{background:#fff8e7;border:1px solid #e7d5a2;padding:16px 20px;border-radius:8px}.grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr);gap:20px;margin-top:24px}.panel{background:#fff;border:1px solid var(--line);border-radius:10px;padding:20px;min-width:0}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px}input,select{padding:10px;border:1px solid #bdcbd2;border-radius:6px;background:#fff;color:var(--ink);font:inherit}input{flex:1;min-width:160px}.table-wrap{overflow:auto;max-height:730px}table{border-collapse:collapse;width:100%;font-size:13px}th{text-align:right;white-space:nowrap;background:#edf3f6;position:sticky;top:0;z-index:1}td,th{padding:10px 8px;border-bottom:1px solid var(--line)}td{text-align:right;vertical-align:top}td:first-child,th:first-child{text-align:left}button.topic{border:0;background:none;padding:0;color:var(--blue);text-align:left;font:inherit;font-weight:650;cursor:pointer;word-break:break-word}tr.active{background:#edf6fb}.badge{display:inline-block;font-size:11px;padding:2px 7px;border-radius:4px;background:#e9eef0;color:var(--muted)}.strong{background:#dff2e8;color:var(--green)}.negative{color:var(--red)}.positive{color:var(--green)}svg{width:100%;height:auto;display:block}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.metric{padding:10px;background:#f3f6f7;border-radius:5px}.metric strong{display:block;font-size:18px}.evidence{border-top:1px solid var(--line);padding:14px 0}.evidence p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}.evidence a,a{color:var(--blue)}details{margin-top:14px}summary{cursor:pointer;font-weight:650}.findings{padding-left:22px}.findings li{margin-bottom:12px}code{font-size:12px}footer{margin-top:24px;font-size:13px}.inline-links{display:flex;gap:16px;flex-wrap:wrap}.chart-label{font:11px system-ui;fill:#526675}@media(max-width:900px){.grid{grid-template-columns:1fr}main{padding:24px 14px}h1{font-size:28px}.table-wrap{max-height:420px}}
</style></head><body><main>
<div class="eyebrow">Local corpus analysis · 17 August – 17 September 2026 · UTC</div>
<h1>Topic spikes &amp; sentiment shifts</h1>
<p class="muted">Full-corpus lexical topic counts and measured engagement trajectories, paired with author-balanced sampled text polarity. No Azure resources used.</p>
<div class="stats" id="stats"></div>
<div class="notice"><strong>Collection break, not a platform-wide trend.</strong> September has dramatically fewer collected posts. Topic spikes use share of each day's unique tweets and within-regime baselines. September 17 is partial and excluded from peak selection. This reduces—but cannot eliminate—collection bias.</div>
<section class="panel" style="margin-top:20px"><h2>What stands out</h2><ul class="findings" id="findings"></ul></section>
<div class="grid"><section class="panel"><h2>Explore the outliers</h2><div class="toolbar"><input id="search" aria-label="Search topics" placeholder="Search a topic or hashtag"><select id="filter" aria-label="Filter topic type"><option value="all">All displayed topics</option><option value="sentiment">Strong sentiment shifts</option><option value="entity">Entity / keyword families</option><option value="hashtag">Hashtags</option></select></div><small id="table-count"></small><div class="table-wrap"><table><thead><tr><th>Topic</th><th>Peak UTC</th><th>Posts</th><th>Share lift</th><th>Polarity Δ</th></tr></thead><tbody id="rows"></tbody></table></div></section>
<section class="panel" id="detail" aria-live="polite"></section></div>
<section class="panel" style="margin-top:20px"><h2>Genuine engagement growth</h2><div id="trajectories"></div><p class="muted">Snapshot deltas are distinct from final popularity. Sampling intervals are irregular; a rate is an average between observations, not a measured minute-by-minute viral curve. Retweet-prefixed posts are not ranked as independent original engagement.</p></section>
<section class="panel" style="margin-top:20px"><h2>Methods and limits</h2><ul><li><strong>Full corpus:</strong> latest observation per numeric tweet ID; max(version, added_at), including ID groups spanning files. All hashtags discovered; 58 explicit, overlapping entity/keyword families additionally measured. This is not exhaustive semantic labeling of every tweet.</li><li><strong>Traction:</strong> exact topic counts and distinct authors; displayed lift is peak share / other complete-day share in the same August or September collection regime. Entity topics also have a language-mix-adjusted sensitivity estimate.</li><li><strong>Sentiment:</strong> whole-post positive-minus-negative model score, −1 to +1. Not stance toward the entity. At most 200 peak and 300 baseline authors; one post per author, normalized text templates capped. Replies/quotes included; RT-prefixed posts excluded.</li><li><strong>Inference:</strong> CardiffNLP multilingual Twitter model. Primary tests only ar/de/en/es/fr/hi/it/pt. Other languages are exploratory. Sarcasm, code-switching, mourning and mixed-target text require caution.</li><li><strong>Strong shift:</strong> minimum 80 supported-language authors per period and 80 in common language strata; |mean shift| ≥0.15; author-bootstrap 95% interval excludes zero; language-adjusted BH q&lt;0.05; adjusted and raw signs agree.</li><li><strong>Uncertainty:</strong> confidence intervals reflect sampling, not model calibration or the unknown collection process. Baselines are retrospective, not causal. Named-event claims in tweets are not externally verified. Media content is not analyzed.</li></ul><details><summary>Exact analysis definitions</summary><pre id="methods" style="white-space:pre-wrap;font-size:12px"></pre></details></section>
<footer><h3>Data and reproducibility</h3><div class="inline-links"><a href="topic-spikes.csv">All supported topic spikes (CSV)</a><a href="sentiment-shifts.csv">Sentiment comparisons (CSV)</a><a href="trajectory-outliers.csv">Engagement trajectory outliers</a><a href="daily-denominators.csv">Daily corpus denominators</a><a href="entity-topics.json">Exact entity matching terms</a><a href="topic-inventory.json">Full topic inventory</a><a href="final-sentiment.json">Model provenance</a></div><p><a href="https://huggingface.co/cardiffnlp/twitter-xlm-roberta-base-sentiment">Sentiment model card</a> · <a href="https://arxiv.org/abs/2104.12250">XLM-T paper</a></p></footer>
</main><script>
const DATA=__DATA__;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('en-US');const fixed=(n,d=2)=>n==null?'—':Number(n).toFixed(d);
let active=null;
const topics=DATA.topics.sort((a,b)=>Number(b.sentiment?.strong_sentiment_shift||false)-Number(a.sentiment?.strong_sentiment_shift||false)||Number(a.low_baseline)-Number(b.low_baseline)||(b.sentiment?.combined_outlier_score||0)-(a.sentiment?.combined_outlier_score||0)||b.spike_score-a.spike_score);
document.querySelector('#stats').innerHTML=[['Observations',DATA.profile.observations],['Unique tweets',DATA.profile.tweets],['Eligible burst candidates',DATA.candidate_topics],['Strong polarity shifts',DATA.sentiment_method.strong_shifts]].map(([label,n])=>`<div class="stat"><strong>${fmt(n)}</strong><span>${esc(label)}</span></div>`).join('');
document.querySelector('#findings').innerHTML=DATA.notes.findings.map(s=>`<li>${esc(s)}</li>`).join('');
document.querySelector('#trajectories').innerHTML=DATA.notes.trajectories.map(s=>`<p>${esc(s)}</p>`).join('');
document.querySelector('#methods').textContent=JSON.stringify({spikes:DATA.spike_method,sentiment:DATA.sentiment_method},null,2);
function plot(series){let w=680,h=205,l=54,r=16,t=20,b=35,max=Math.max(...series.map(d=>d.per_100k),1);const x=i=>l+i*(w-l-r)/(series.length-1),y=v=>h-b-v/max*(h-t-b);let path=series.map((d,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(d.per_100k).toFixed(1)).join(' ');let sep=series.findIndex(d=>d.day==='2026-09-01');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Topic posts per 100,000 collected unique tweets by day"><line x1="${l}" y1="${y(0)}" x2="${w-r}" y2="${y(0)}" stroke="#cad6dd"/><text x="0" y="${t+4}" class="chart-label">${fixed(max,1)}</text><text x="20" y="${y(0)}" class="chart-label">0</text><text x="${l}" y="12" class="chart-label">posts / 100k collected tweets</text>${sep>=0?`<line x1="${x(sep)}" y1="${t}" x2="${x(sep)}" y2="${h-b}" stroke="#b58d35" stroke-dasharray="4 4"/><text x="${x(sep)+5}" y="${t+12}" class="chart-label">Sep collection regime</text>`:''}<path d="${path}" fill="none" stroke="#146b9e" stroke-width="2.4"/>${series.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d.per_100k)}" r="3" fill="${d.partial_day?'#b58d35':'#146b9e'}"><title>${esc(d.day)}: ${fixed(d.per_100k)} per100k; ${fmt(d.tweets)} posts${d.partial_day?' (partial day)':''}</title></circle>`).join('')}<text x="${l}" y="${h-8}" class="chart-label">Aug 17</text><text x="${w-r-72}" y="${h-8}" class="chart-label">Sep 17*</text></svg>`}
function detail(topic){active=topic.topic;let s=topic.sentiment;let shift=s?.mean_shift;document.querySelector('#detail').innerHTML=`<div class="eyebrow">${esc(topic.family)}</div><h2>${esc(topic.label)}</h2><p>${esc(topic.interpretation||'Lexical topic match. Inspect the exact terms and supporting posts before assigning a real-world cause.')}</p>${plot(topic.series)}<div class="metrics"><div class="metric"><strong>${fmt(topic.peak_tweets)}</strong>peak-day posts · ${esc(topic.peak_day)}</div><div class="metric"><strong>${fixed(topic.share_lift,1)}×</strong>normalized share lift</div><div class="metric"><strong>${fmt(topic.peak_authors)}</strong>distinct peak-day authors</div><div class="metric"><strong>${fixed(topic.peak_rt_fraction*100,1)}%</strong>RT-prefixed posts</div></div><p class="muted">Language-adjusted share lift: ${topic.language_adjusted_share_lift==null?'not measured for this hashtag':fixed(topic.language_adjusted_share_lift,1)+'×'}. ${topic.low_baseline?'Very low baseline: lift is unstable.':''} ${topic.window_boundary_peak?'Peak touches a window/regime boundary.':''}</p>${s?`<h3>Sampled text polarity</h3><span class="badge ${s.strong_sentiment_shift?'strong':''}">${s.strong_sentiment_shift?'Strong shift under stated rule':'Exploratory / does not pass strong-shift rule'}</span><div class="metrics"><div class="metric"><strong>${fixed(s.peak_sentiment.mean)}</strong>peak · n=${s.peak_sentiment.n}</div><div class="metric"><strong>${fixed(s.baseline_sentiment.mean)}</strong>baseline · n=${s.baseline_sentiment.n}</div></div><p>Mean shift: <strong class="${shift<0?'negative':'positive'}">${fixed(shift)}</strong> ${s.shift_ci95?'· 95% bootstrap interval ['+s.shift_ci95.map(v=>fixed(v)).join(', ')+']':''}<br>Language-adjusted shift: ${fixed(s.language_adjusted_shift)} · BH q=${s.language_adjusted_q==null?'—':s.language_adjusted_q.toExponential(2)}</p><small>Excluded from primary language tests: ${s.unsupported_peak_posts} peak / ${s.unsupported_baseline_posts} baseline sampled posts. A positive score is positive wording, not necessarily approval of the event.</small>`:'<p class="muted">Sentiment was not sampled for this topic.</p>'}<h3 style="margin-top:22px">Supporting high-engagement non-RT posts</h3>${topic.evidence.length?topic.evidence.slice(0,5).map(e=>`<article class="evidence"><a href="https://x.com/i/web/status/${encodeURIComponent(e.id)}" target="_blank" rel="noopener noreferrer">${esc(e.id)}</a><small> · ${esc(e.lang)} · ${fmt(e.like_count||0)} likes · ${fmt(e.views_count||0)} views</small><p>${esc(e.body.slice(0,900))}</p></article>`).join(''):'<p class="muted">See corpus tables for this unsampled topic.</p>'}`;renderTable()}
function renderTable(){let q=document.querySelector('#search').value.toLowerCase(),f=document.querySelector('#filter').value;let filtered=topics.filter(t=>(t.label+' '+t.topic+' '+t.family).toLowerCase().includes(q)&&(f==='all'||f==='sentiment'&&t.sentiment?.strong_sentiment_shift||f==='entity'&&t.topic.startsWith('entity:')||f==='hashtag'&&t.topic.startsWith('#')));document.querySelector('#table-count').textContent=`${filtered.length} displayed topics; full candidate ranking contains ${fmt(DATA.candidate_topics)} topics in the CSV.`;document.querySelector('#rows').innerHTML=filtered.map(t=>`<tr class="${active===t.topic?'active':''}"><td><button class="topic" data-topic="${esc(t.topic)}">${esc(t.label)}</button>${t.sentiment?.strong_sentiment_shift?'<br><span class="badge strong">sentiment shift</span>':''}</td><td>${esc(t.peak_day.slice(5))}</td><td>${fmt(t.peak_tweets)}</td><td>${t.low_baseline?'New / sparse':fixed(t.share_lift,1)+'×'}</td><td>${fixed(t.sentiment?.mean_shift)}</td></tr>`).join('');document.querySelectorAll('button.topic').forEach(b=>b.addEventListener('click',()=>detail(topics.find(t=>t.topic===b.dataset.topic))))}
document.querySelector('#search').addEventListener('input',renderTable);document.querySelector('#filter').addEventListener('change',renderTable);detail(topics[0]);
</script></body></html>'''
(out/'report.html').write_text(html.replace('__DATA__',serialized))
print(f"Rendered {len(chosen)} topics to {out/'report.html'}")
